### ISSUE TITLE
rbac 无法创建表

### ISSUE THREAD

**Issue by taototokay** [yang-va/onlinestudy#3]
(env) G:\work\pythonproject\OnlineStudy>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "G:\work\pythonproject\env\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "G:\work\pythonproject\env\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "G:\work\pythonproject\env\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "G:\work\pythonproject\env\lib\site-packages\django\core\management\base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "G:\work\pythonproject\env\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "G:\work\pythonproject\env\lib\site-packages\django\core\management\commands\migrate.py", line 82, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "G:\work\pythonproject\env\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "G:\work\pythonproject\env\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "G:\work\pythonproject\env\lib\site-packages\django\db\migrations\loader.py", line 270, in build_graph
    raise exc
  File "G:\work\pythonproject\env\lib\site-packages\django\db\migrations\loader.py", line 244, in build_graph
    self.graph.validate_consistency()
  File "G:\work\pythonproject\env\lib\site-packages\django\db\migrations\graph.py", line 243, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "G:\work\pythonproject\env\lib\site-packages\django\db\migrations\graph.py", line 243, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "G:\work\pythonproject\env\lib\site-packages\django\db\migrations\graph.py", line 96, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration generic.0001_initial dependencies reference nonexistent parent node ('rbac', '0001_initial')

应该是版本不对，下面是对应的版本：
Package                Version
---------------------- ---------
alipay-sdk-python      3.3.92
attrs                  19.1.0
Automat                0.7.0
autopep8               1.4.4
backports.csv          1.0.7
certifi                2019.6.16
chardet                3.0.4
constantly             15.1.0
cycler                 0.10.0
defusedxml             0.6.0
diff-match-patch       20181111
Django                 2.1
django-cors-headers    3.0.2
django-import-export   1.2.0
django-simpleui        2.1.5
djangorestframework    3.10.2
et-xmlfile             1.0.1
geetest                3.2.1
hyperlink              19.0.0
idna                   2.8
incremental            17.5.0
jdcal                  1.4.1
kiwisolver             1.1.0
matplotlib             3.1.1
numpy                  1.17.0
oauthlib               3.1.0
odfpy                  1.4.0
openpyxl               2.6.2
pandas                 0.25.0
Pillow                 6.1.0
pip                    19.2.1
pyasn1                 0.4.6
pycodestyle            2.5.0
pycrypto               2.6.1
pycryptosat            0.2.0
PyHamcrest             1.9.0
PyJWT                  1.7.1
PyMySQL                0.9.3
pyparsing              2.4.2
python-dateutil        2.8.0
python3-openid         3.1.0
pytz                   2019.2
PyYAML                 5.1.2
redis                  3.3.6
requests               2.22.0
requests-oauthlib      1.2.0
rsa                    4.0
setuptools             28.8.0
six                    1.12.0
social-auth-app-django 3.1.0
social-auth-core       3.2.0
sqlparse               0.3.0
tablib                 0.13.0
Twisted                19.2.1
urllib3                1.25.3
xlrd                   1.2.0
xlwt                   1.3.0
zope.interface         4.6.0

**Comment by taototokay** [comment]
已经解决了。

**Comment by Christings** [comment]
我也遇到了

**Comment by Christings** [comment]
不是版本的问题，是generic的问题

**Comment by tenderzada** [comment]
我也遇到了，请问如何解决。

**Comment by tenderzada** [comment]
> 不是版本的问题，是generic的问题

请问如何解决呢

**Comment by 137561160** [comment]
你们怎么解决的啊？

**Comment by 137561160** [comment]
https://blog.csdn.net/yongferic1/article/details/108895091 这样就解决了。哈哈
